### ISSUE TITLE
incorrect model_id for batch_info and scores

### ISSUE THREAD

**Issue by atyoshioka** [petabi/review-database#145]
When inserting or updating a model, `review` calls the `model::Model::into_storage` method first and then calls either the `Database::add_model` method or the `Database::update_model` method. The issue here is that when `batch_info` and `scores` are created in the `into_storage` method, they are assigned a value of 0 for the `id` because the actual `id` from the Postgres database is unknown at that point. 

To address this, `batch_info` and `scores` should be created after the insertion or update, as the Postgres database returns the correct `id` of the model.

**Comment by minshao** [comment]
It is fixed in petabi/review#1567, I didn't make the PR yet mainly because review-web hasn't been released (now it's WIP to present the solution). The PR is not exactly as you requested. I chose to update the id in `batch_info` and `scores` afterwards, mainly to keep the interface a bit simpler.
