### ISSUE TITLE
Add migration according to `Node` change

### ISSUE THREAD

**Issue by sehkone** [petabi/review-database#157]

**Comment by sophie-cluml** [comment]
This issue is to support `Node 설정 상세 규격` project, in https://www.notion.so/cluml/Node-d1a58fd7fbb8488db1b33157eae8ad77?pvs=4

**Comment by sophie-cluml** [comment]
Resolved by ee18807ccb32053a8d300cb12bd2747ff708afa5

**Comment by sophie-cluml** [comment]
@sehkone I do not have rights to close this issue, please close.

**Comment by sehkone** [comment]
Closed by #161
