### ISSUE TITLE
Migrate  `CsvColumnExtra` to RocksDB

### ISSUE THREAD

**Issue by minshao** [petabi/review-database#197]
Upon closer inspection, it has been observed that:
* the `csv_column_extra` table is currently accessible only through the review-web interface for users. 
* However, essential operations such as `insert`, `delete`, and `update` are not supported in user interface. 
* Consequently, it appears that the table has become obsolete, leading to the suggestion that it should be deleted.

@sehkone @syncpark If this deprecation is approved, it should be noted that upon completion, the data stored by users in the `csv_column_extra` table will be lost in the subsequent release of the review. Unfortunately, the lost data will be unrecoverable. Please let me know your thoughts on this, appreciate it~

**Comment by sehkone** [comment]
@minshao , review-web has two functions: `add_csv_column_extra` and `update_csv_column_extra`

**Comment by minshao** [comment]
Thanks for the help. Then I'll just migrate the table to RocksDB

**Comment by minshao** [comment]
Resolved with #201
