### ISSUE TITLE
Change `node_map` to use IndexedMultimap struct

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-database#208]
`node_map` may have an as-is version of the node, and to-be version of the node. We only need to store 2 versions of the node as of now, ~~but it might be requested in the future to be able to store multiple versions of node item in the db.~~ This calls for the need to utilize IndexedMultimap for `node_map`.

**Comment by msk** [comment]
Before we proceed, I'd like to better understand the specific requirements and motivations behind this suggestion.

Could you clarify the scenarios or use cases where storing multiple versions of a node becomes necessary? My current understanding is that the proposal aims to address the need for maintaining both an as-is and to-be version of nodes, with the possibility of expanding to more versions in the future. This introduces questions about the optimal structure to accommodate the hierarchical nature of node versions, where each node ID could have multiple instances, each relevant at different times.

Given this, is `IndexedMultimap` the most suitable abstraction for our needs? It treats every element equally, without an inherent hierarchy among the nodes and their versions. Depending on our requirements, alternative approaches could include storing all versions within a single `IndexedMap` entry or using a separate Column Family for different node versions. This choice significantly impacts how we query and interact with node data, especially in operations like `nodeList`.

To make an informed decision, it would be helpful to discuss:

- The expected usage patterns and how they influence the choice of data structure.
  - How frequently will node versions be accessed or updated? Will there be a need to access historical data often, or is the focus primarily on the current and immediate next versions?
  - What is the expected ratio of read to write operations? The index structure used by `IndexMap` and `IndexMultimap` may not be suitable for frequent inserts/deletes.
  - How complex are the queries expected to be? Will they often filter or sort nodes based on attributes like timestamps, version status (active, future, past), or other criteria?
- How we intend to present node versions in `nodeList`: as a comprehensive list with timestamps, focusing on active versions, or another method?
  - Should queries by default return all versions of a node, or just the active ones?
  - If multiple versions are included in query results, should they be sorted by their timestamps? Sorting could help users understand the chronological progression of changes but might introduce additional computational overhead.
  - How should historical versions be accessed? Options include on-demand access through specific queries or as part of the standard query response.
  - How will the chosen approach affect the API's design? Should other queries taking node as an argument be updated to allow users to designate a specific version of a node?

**Comment by msk** [comment]
The approach of consolidating `asis` and `tobe` within a single node structure to handle versioning aligns well with the requirements. I have a few points for consideration:

1. Based on the two-step process you described, it appears that `asis` will always contain data once a node is initially set up. If my understanding is correct, and `asis` is indeed always populated during the node's lifecycle in the database, then it might be more straightforward to keep `asis` as a non-Optional field. This could simplify the logic for accessing `asis` data, as we wouldn't need to unwrap an `Option` every time we access it. Could you confirm if there are scenarios where `asis` might be `None`?

2. Utilizing `asis`'s `name` as the key for the `Node` struct could offer advantages in terms of readability and natural sorting in queries. I understand the concern about the potential need to change keys, but RocksDB's capabilities should allow us to manage such changes effectively through a delete-and-insert operation. This approach could maintain a more intuitive organization of nodes, especially in `nodeList` queries, where alphabetical sorting might be desirable.

3. Adjusting the naming of `asis` and `tobe` to `as_is` and `to_be` would align better with Rust's conventional naming practices, enhancing readability and reducing the chance of confusion among developers familiar with these conventions.

**Comment by sophie-cluml** [comment]
1 & 2 : If users do save-only for the Node item in the initial setup, then `asis` is `None` and `tobe` is `Some`. When users press the apply button, then `tobe` will be moved to `asis`, and from then on, `asis` will always be `Some`.
3 : I agree.

**Comment by msk** [comment]
Given this nature between `asis` and `tobe`, exploring the possibility of using either `asis`'s name or `tobe`'s name as the key could indeed be a viable approach, since at least one of them should be `Some`.

I recognize there might be nuances or considerations I haven't fully appreciated. Therefore, I'm flexible regarding the final ordering scheme, provided it supports our ordering requirements for the `nodeList` query effectively. If there are other strategies or approaches you believe could better accommodate our needs, I'm keen to discuss those as well.

**Comment by sophie-cluml** [comment]
Sounds great. I was hesitant between using something_like_uuid and using either asis's name or tobe's name, and latter looks great as well. I have below in mind, if you think otherwise please let me know! Please tell me if we are good to go with this, so that I can close this issue and the connected PR. Thank you for taking time on this issue by the way!

```rust
// to-be implementation
impl Indexable for Node {
    fn key(&self) -> &[u8] {
        if let Some(asis) = &self.value.asis {
            asis.name.as_bytes()
        } else if let Some(tobe) = &self.value.tobe {
            tobe.name.as_bytes()
        } else {
            error!("Both asis and tobe are None in Node!");
            // return a empty slice
            &[]
        }
    }
```

**Comment by sophie-cluml** [comment]
Sure! Panic I will do. Let me close the PR and this issue. I thank you!
