### ISSUE TITLE
Do not use `panic!` in `Node` by placing `name` out of `as_is` and `to_be`

### ISSUE THREAD

**Issue by sehkone** [petabi/review-database#243]
In `node.rs`, the `key` calls `panic!` conditionally. This assumes there is no such case, but since it's not 100% guaranteed we need to handle this in a different manner.

**Comment by sophie-cluml** [comment]
Do you have suggestions how to do it differently?
For reference, previous discussion on panicking https://github.com/petabi/review-database/issues/208#issuecomment-1942137773

**Comment by sehkone** [comment]
@sophie-cluml and @msk,

Firstly, I would like to apologize for my late suggestion and for any inconvenience caused. In my view, it would be more effective to remove the `name` from the `NodeSetting` and place it directly within the `Node`. I believe that a `name` should be a mandatory and unique attribute for a `Node`, making it preferable to include it in the `Node` itself rather than in the `as_is` or `to_be` settings. This approach ensures that whenever a key is created, it can always be associated with a `name`.

**Comment by sehkone** [comment]
By adopting this approach, modifying the `name` requires a distinct process beyond simply using the `to_be`. However, this extra step is not overly burdensome, and given the `name`s unique significance, it warrants individual attention.

**Comment by sophie-cluml** [comment]
@sehkone Looks good to me.
