### ISSUE TITLE
[TI SAS] Make GraphQL subscription function to send event messages to API gateway

### ISSUE THREAD

**Issue by syncpark** [petabi/review-database#25]
aicelab/api-gateway#1

This issue only applies to TI SAS project.

To support Web UI of TI SAS project,
1. Make GraphQL subscription function to send detected event messages received from Hog and REconverge to TI SAS API Gateway.

**Comment by syncpark** [comment]
The detected events for TI SAS project is not just for display it to UI. TI SAS process includes the triage procedure and TI extraction procedure like IP address, UI, FQDN, ...

With GraphQL API of REview, it's difficult to locate the exact position which event is retrieved, because Hog and REconverge have different delay in time

**Comment by msk** [comment]
> The detected events for TI SAS project is not just for display it to UI. TI SAS process includes the triage procedure and TI extraction procedure like IP address, UI, FQDN, ...
> 
> With GraphQL API of REview, it's difficult to locate the exact position which event is retrieved, because Hog and REconverge have different delay in time

As it currently stands, REview is not designed to operate in a push mode, which would involve asynchronously sending data to remote nodes. Adapting REview-database to push events to TI SAS would significantly alter the existing architecture and add complexity to the REview codebase.

Instead, I propose extending REview's GraphQL API to include subscriptions for events, allowing the TI SAS project to receive events from REview using GraphQL subscriptions. This approach aligns better with the current design and should be more straightforward to implement.

Please let me know your thoughts on this alternative and if you have any questions or concerns.

**Comment by syncpark** [comment]
I searched and read some text from internet about GraphQL subscription.

I think GraphQL subscription is best choice. I'll change the issue to use GraphQL subscription.

**Comment by msk** [comment]
Superseded by aicers/review-web#7.
