### ISSUE TITLE
Remove Unused Fields from Node Struct Related to REconverge

### ISSUE THREAD

**Issue by msk** [petabi/review-database#273]
In a recent commit (ee18807), fields `reconverge_giganto_ip` and `reconverge_giganto_port` were added to the `Node` struct. These fields are intended to configure REconverge to fetch data from a Giganto instance for analysis. However, different models in REconverge may analyze data from different multiple Giganto instances, and thus REconverge stores the relevant IP addresses and ports directly in the model definitions within the model ColumnFamily in RocksDB.

## Issue

Storing a single Giganto address and port in the node ColumnFamily does not align well with REconverge's operational dynamics, as each model may need to interact with different Giganto instances. It seems that these fields in the `Node` struct might not be used effectively based on the current system design and could potentially lead to confusion or misconfiguration.

## Suggested Action

I propose removing `reconverge_giganto_ip` and `reconverge_giganto_port` from the `Node` struct to streamline the node configuration and better reflect the system's architecture. This change would help ensure that node settings remain relevant and do not carry unnecessary or misleading information.

**Comment by sehkone** [comment]
@msk 
Thank you for reminding me of how REconverge exactly functions, about which I had been confused for a while. I will have someone take care of this.
