### ISSUE TITLE
Send all fields of detected events to Syslog

### ISSUE THREAD

**Issue by syncpark** [petabi/review-database#274]
Related to: https://github.com/aicers/patio/issues/45, https://github.com/aicers/patio/issues/85

- [x]  All fields of detected events should be sent to Syslog
- [x]  The delimiter (currently comma(,)) should not be included in the field content. The comma delimiter may need to be changed.

**Comment by sehkone** [comment]
@syncpark 
Could you remove the links to the private locations?
