### ISSUE TITLE
Update `tables::node::Settings` with migration, for #273, #280, #281, and #287

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-database#282]
This issue is to group these three issues below, which calls for a change in `tables::node::Settings` and requires subsequent migration code.
- [x] #273 
- [x] #280 
- [x] #281 
- [x] #283 
- [x] #287 

It looks like it is rather efficient to handle these issues in a single PR with a single migration logic for `Node`, than to have three PRs with three migration steps, so I grouped these into this single issue.

**Comment by sophie-cluml** [comment]
@msk Would it be okay to approach this way?

**Comment by msk** [comment]
> @msk Would it be okay to approach this way?

Fine with me.

**Comment by sophie-cluml** [comment]
I added another https://github.com/petabi/review-database/issues/283 just a minute ago, and it also is about `tables::node::Settings`, so added it as a sub task in this group.

**Comment by sophie-cluml** [comment]
And I'd like to start working on this task group.
