### ISSUE TITLE
Modify `Event` enum and add migration code

### ISSUE THREAD

**Issue by kimhanbeom** [petabi/review-database#284]
## Background

- We are working on updating the gigatno-client version to `0.17.0` for all modules that use giganto-client.
- In giganto-client `0.17.0`, fields in the SSH, HTTP, SMTP, CONN, NTLM, and TLS protocols have changed, and REview that receive detected events from these protocols also need to change the field values in `Event` and add migration code.

## Detail task

- Modify the fields in `Event` corresponding to SSH, HTTP, SMTP, CONN, NTLM, and TLS protocols.
- Add migration functionality based on changes to the `Event` field.

**Comment by kimhanbeom** [comment]
I'll take care of the current issue.

**Comment by sophie-cluml** [comment]
[TEST] I've been asked to comment for testing github comment and assignee option, so we're commenting for a while. We'll remove it after testing shortly. Sorry for inconvinience.
