### ISSUE TITLE
Fix mismatched event category

### ISSUE THREAD

**Issue by syncpark** [petabi/review-database#301]
1. `EventCategory` value  for `RdpBruteForce` event must be fixed
    It's defined to `EventCategory::Exfiltration` in **src/event/rdp.rs**, but `EventCategory::Discovery` is used in **src/event.rs: fn count_category()**
2. `EventCategory` for `HttpThreat` event must be fixed
    `EventCategory::HttpThreat` is defined In **src/event/http.rs**, but `EventCategory::Reconnaissance` is used in **src/event.rs: fn count_category()**
3. Modify the `count_category()` function to use `category()` member function instead of constant value.

**Comment by syncpark** [comment]
`EventCategory::HttpThreat` is not exist in any kind of events after this change is applied.
And this change may affect to the search action in UI with category `HttpThreat`.

Originally there is no `HttpThreat` category in the MITRE, but we've inserted it because the only model using unsupervised learning was HTTP event analyzing model at the time.

Now we have to make decision whether to maintain `HttpThreat` category or not.
If not, we can find the detected events from the HTTP event analyzing model in `Reconnaissance` category instead of `HttpThreat`.

@sehkone @MW-Kim @msk What do you think about this?

**Comment by sehkone** [comment]
@syncpark @msk @MW-Kim 
If we only have the reconnaissance category, people might think our unsupervised model cannot detect any threats from other categories, which would look pretty bad. First of all, I want to know whether this is true or not. I strongly hope our unsupervised model can detect a wide range of threats from various categories. Could you share your thoughts on this?

**Comment by MW-Kim** [comment]
@sehkone @msk @syncpark 
Currently, threats have a Mitre-based category. However, the HTTP threat is the `HTTPThreat` category, not the Mitre-based category. If new unsupervised learning models are added in the future, detection can be shown in various miter-based categories.

**Comment by sehkone** [comment]
@MW-Kim @syncpark, do we need to develop new models to add extra categories, or can we simply expand the labels to achieve this?

**Comment by syncpark** [comment]
@sehkone 
Is there really a need to simply compare supervised analysis and unsupervised analysis?
In addition to the intersection between the two, I think it would be good to highlight the characteristics of unsupervised analysis. For example, focusing on outliers, small-sized clusters, or new clusters.

**Comment by syncpark** [comment]
@sehkone 
I also want to apply various categories to the detected events in the HTTP unsupervised model. But the category is attached to the events by the REview not by the REconverge or TI rule itself.

**Comment by syncpark** [comment]
It is possible to modify the procedure by pre-defining categories in the supervised model (Hog) or unsupervised model (REconverge, especially TI rules) and sending them to the REview.

**Comment by sehkone** [comment]
@msk @MW-Kim @syncpark 
I talked to @MW-Kim and @syncpark yesterday:
- Even now, our unsupervised learning analysis includes a few categories in addition to reconnaissance.
- However, under the current code, the learner cannot provide which category each event belongs to.
- Therefore, we need to modify our codebase to allow the learner to send the category of each event to the central server.

**Comment by sehkone** [comment]
@syncpark 

As I told you repeatedly, this repository is public, so DO NOT use the name of the private repositories.
