### ISSUE TITLE
Migrate `Agent::config` to have full configuration

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-database#306]
Currently, only a few of the individual agent's configuration items are stored in the review-database. However, we want to move towards storing full configuration in the review-database. In order to move in this direction, we want to write code that migrates the current `Agent::config` to have full configuration items. This issue does not aim to change the type of `Agent::config`. We see the targets of this migration as `node_map`, due to Giganto, and `agents_map`, due to agents other than Giganto.

**Comment by sehkone** [comment]
@sophie-cluml,
I don’t think the "more configuration items" you described align exactly with what we discussed. The configuration items should comprehensively cover everything each agent needs since we require every agent to fetch its complete configuration from the central server.

**Comment by sophie-cluml** [comment]
Thank you for the fix!
