### ISSUE TITLE
Add method for `update` in TrustedDomain

### ISSUE THREAD

**Issue by henry0715-dev** [petabi/review-database#327]
### Description

Add Rocks Db table's `update` method
- update method to modify with input data

### Reference
https://github.com/aicers/review-web/issues/2

**Comment by sehkone** [comment]
I don't get why this `get` method is required. @sophie-cluml and @henry0715-dev, could you share your thoughts?

**Comment by henry0715-dev** [comment]
@sehkone 
https://github.com/petabi/review-database/blob/main/src/tables/accounts.rs#L72-L155

Do you think of applying similar to the implementation of `update` in `accounts`?

**Comment by henry0715-dev** [comment]
<img width="1403" alt="스크린샷 2024-08-20 오전 9 00 07" src="https://github.com/user-attachments/assets/30d39b87-c2a6-4ceb-b7f2-b6548c2be081">

You can change the domain name that is identified, so if you look it up by get, I think there will be a way to perform the insert function.

**Comment by sehkone** [comment]
> @sehkone https://github.com/petabi/review-database/blob/main/src/tables/accounts.rs#L72-L155
> 
> Do you think of applying similar to the implementation of `update` in `accounts`?

It is necessary to check if the old value is the same as the stored value to ensure that no attempt has been made to change the value. This is a type of concurrency issue. Additionally, we need to consider the situation where the primary key, the `name`, is changed. In that case, the deletion of the previous entry and the addition of the new one should happen consecutively and in an atomic manner.

**Comment by henry0715-dev** [comment]
The question was regarding the scenario where the domain name for "old" is not provided as a parameter. To implement the functionality using only the update function, I will process it by accepting both the "old" and "new" domain names.

**Comment by sehkone** [comment]
> The question was regarding the scenario where the domain name for "old" is not provided as a parameter. To implement the functionality using only the update function, I will process it by accepting both the "old" and "new" domain names.

We don't need to consider the case where no `old` is given, in the most tables. The `Account` is special.

**Comment by sehkone** [comment]
> @sehkone https://github.com/petabi/review-database/blob/main/src/tables/accounts.rs#L72-L155
> 
> Do you think of applying similar to the implementation of `update` in `accounts`?

BTW, it would have been better if you had provided more explanation with your question.

**Comment by sehkone** [comment]
> I don't get why this `get` method is required. @sophie-cluml and @henry0715-dev, could you share your thoughts?

I think I didn't hear anything regarding this.

**Comment by sophie-cluml** [comment]
https://github.com/petabi/review-database/issues/327#issuecomment-2298025059
-> I think `get` is not necessary.

**Comment by henry0715-dev** [comment]
I have removed the contents of `get`.
