### ISSUE TITLE
Fix wrong indexed map name for `SamplingPolicy`

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/review-database#367]
https://github.com/petabi/review-database/blob/76a307b7e762e8f62984ad6b41e77a805f046981/src/tables/sampling_policy.rs#L93-L101

@MW-Kim found that a wrong name was given to the `SamplingPolicy` indexed map, and suggested changing `super::NETWORKS`  to `super::SAMPLING_POLICY` in the above code.

And I personally think this might suggest that review-database 0.27.0 ~ 0.31.0 needs to be yanked.

**Comment by sehkone** [comment]
> And I personally think this might suggest that review-database 0.27.0 ~ 0.31.0 needs to be yanked.

These haven't been deployed and won’t be either, so I don’t think yanking them is necessary.
