### ISSUE TITLE
Database migration fails

### ISSUE THREAD

**Issue by atyoshioka** [petabi/review-database#37]
Steps to reproduce
1. Run review `0.20.0` and REconverge. Store the clustering results into a Postgres DB.
2. Update review to `0.21.0` and run.
3. review throws a migration error:

```
2023-05-03T16:24:32.159055Z ERROR review: An error occurred while starting REview: failed to connect to the PostgreSQL database: migration error: Failed to run 2023-04-13-211209_add_source with: dimension values cannot be null
``` 

Note that no error seems to occur if the Postgres DB is empty.

**Comment by minshao** [comment]
* Could you provide more information on what's stored in the database before running 0.21.0?
* Did you run anything to trigger the error or it just showed up when review is started?

I tried running with an non-empty Postgres DB and couldn't reproduce it so far, what I did was:
* run previous REconverge to train and analyze with Review 0.20.0,
* upgrade REconverge (tip of main) and Review 0.21.0 and run again. 

I didn't see the error that you mentioned. (finding other non-related issue though)

**Comment by atyoshioka** [comment]
Look like this issue happens when the value of `event_ids` column is empty.

```
review008=# select id, event_ids from cluster where id = 822;
 id  | event_ids 
-----+-----------
 822 | {}
(1 row)

review008=# UPDATE cluster SET event_sources = ARRAY_FILL(''::TEXT, ARRAY[array_length(event_ids, 1)]) where id = 822;
ERROR:  dimension values cannot be null
```

**Comment by minshao** [comment]
I see, since in the database, `event_ids` column is defined as `NOT NULL`, I was assuming it shouldn't be empty, so the script didn't consider the case when it is empty. Do you know by any chance know how the empty value got into the database?

**Comment by atyoshioka** [comment]
To be precise, the value of `event_ids` is not `NULL` but an empty array. I could be wrong but I believe that this could happen when a cluster is created from a training file.

**Comment by minshao** [comment]
I see~ I think I know how to fix it~ Thank you!

On a side note, kind of wondering why would reconverge sent a cluster or outlier without any event_id attached.
