### ISSUE TITLE
Remove `unwrap` & Add clippy lint option to check the use of `unwrap`

### ISSUE THREAD

**Issue by dayeon5470** [petabi/review-database#375]
## Background
- The development rules for our product say that we should use `expect` instead of `unwrap` in situations where we are confident that panic will not necessarily occur.
- We should also make sure that the code we write in the future follows the same rules. 
- Therefore, we should proceed with the modification as shown below

## Task
- Remove unwrap(), which is used against the rules
- Add a lint option to the Clippy part of ci.yml: -W clippy::unwrap_used

**Comment by msk** [comment]
Resolved in ac07e6d3ab73f23ea3e6f2d7cfba0b4fd5472beb.
