### ISSUE TITLE
Too many outlier events in `outliers` database

### ISSUE THREAD

**Issue by syncpark** [petabi/review-database#92]
I tried to count the outlier events during the migration from database 0.5 to 0.12.
Outlier events counted up to 240_000_000 and are still increasing.

I think the count includes unnecessary events.
Outlier events should be modified to keep only the necessary events.

**Comment by msk** [comment]
Indeed, we are currently storing more outliers than required for the subsequent round of clustering. This practice was implemented in response to a suggestion from @sehkone who noted that outliers from previous rounds may get deleted, while users could still find value in examining them later.

Consequently, we've allowed for the retention of these outliers for user reference. However, your point on optimizing the database size is well taken. To manage this, we should establish a clear policy regarding the retention period for outliers from earlier rounds.

The proposed policy should specify a reasonable duration or condition after which outliers can be removed. Importantly, it's vital that we communicate this policy effectively with our users. This would ensure they comprehend that outliers from significantly older rounds may not be accessible, helping to set accurate expectations.

@sehkone, as the proponent of retaining outliers, we'd value your input on this topic. Do you have any thoughts or suggestions regarding the outlier retention policy we are considering?

**Comment by sehkone** [comment]
Outliers are stored according to their clustering timeline, and the `outliers` API currently only returns those identified by the most recent clustering process. Regarding this, if I am wrong, please correct me. To ease the storage burden, it would be better to retain only the outliers identified within the last two weeks. However, outliers saved by the users will continue to be stored indefinitely. @msk  is the `preserveOutliers` API responsible for saving outliers? Consequently, 'rankedOutliers' will return all user-saved outliers older than two weeks, as well as all outliers identified in the last two weeks, combined.

My initial motivation to retain all historical outliers was to identify potential threats discovered later by a third party, assuming they were previously identified as outliers. However, I now realize my understanding was slightly misconstrued. As the clustering process continues, outliers get updated, but this includes both current and historical data, so long as they qualify as outliers. It's incorrect to say that the latest clustering results don't encompass historical data.

I was under the impression that as clustering evolved, it would lean towards tagging more recent data as outliers, overshadowing historical data. But given that outlier classification doesn't depend heavily on the clustering timeline, and that the most recent outliers are more precisely classified, I see little advantage in storing all past outliers.

@msk , could you confirm if my current understanding is accurate?

**Comment by msk** [comment]
You're absolutely correct, @sehkone. The clustering process doesn't heavily favor recent data as outliers, and with each round, the process does indeed take into account both current and historical data. Therefore, the most recent clustering process should always present the most accurately classified outliers. I commend your insight and adaptation on this issue.

As for the implementation plan, here's how we can approach it:

1. When REview receives outliers at time $T$ from REconverge and stores them into the database, it will initiate a cleanup process.

2. The cleanup process will scan through older outlier records in the database. It will identify any event that fulfills the following criteria:
    - Has a timestamp earlier than $T$.
    - Is older than two weeks. This duration will be defined as a constant in the code, let's call it `OUTLIER_RETENTION_PERIOD`.
    - The event has not been explicitly saved by a user.

3. Any event fulfilling all these criteria will be flagged for deletion from the database.

4. Once the process has scanned all relevant records, it will batch delete the flagged records from the database. It's crucial to ensure the deletion process does not interfere with the ongoing storage or retrieval of outliers.

5. We'll then adjust our `preserveOutliers` API to align with this new policy and update the `rankedOutliers` and `savedOutliers` to correctly reflect the changes.

6. After implementing these changes, we'll conduct thorough testing to ensure the system works as expected. We also need to monitor the system closely post-implementation to address any potential issues that may arise.

7. Concurrently, we'll prepare a clear and detailed communication to our users regarding this change. It will outline the changes to the policy, the reasons for the change, and the impact on them. 

This approach will help optimize our database storage while preserving the most relevant outliers for the users. Thank you both for your contributions to this conversation, and let's move forward with this plan.

**Comment by msk** [comment]
Resolved in REview 0.27.2.
